name: Update Canonical Tags

on:
  workflow_dispatch:

jobs:
  update-canonical-tags:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Find and update canonical tags in HTML files
      run: |
        find . -name "*.html" | while read htmlFile; do
          tempFile="${htmlFile}.tmp"
          # Process the file to update canonical links
          awk '{
            if ($0 ~ /<link rel="canonical"/) {
              sub(/\.html"/, "\"", $0)
            }
            print $0
          }' "$htmlFile" > "$tempFile"
          mv "$tempFile" "$htmlFile"
        done

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update canonical href tags in HTML files" || echo "No changes to commit"
        # Use the token to push changes
        git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
        git push
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
